In [58]:
import pandas as pd
import numpy as np

movie = pd.read_csv("../ml-latest-small/movies.csv")
movie = movie.set_index("movieId")
movie['year'] = movie['title'].str.extract("(\(\d\d\d\d\))")
movie['year'] = movie['year'].str.extract("(\d\d\d\d)")
movie.sample(5, random_state = 42)
movie['year'] = movie['year'].fillna(np.nan)

genres_unique = []
for item in list(movie['genres'].apply(lambda x: x.split('|'))):
    for i in item:
        genres_unique.append(i)

genres_unique = list(set(genres_unique))

genres = movie['genres'].str.get_dummies(sep = "|")

In [23]:
ratings = pd.read_csv("../ml-latest-small/ratings.csv")
ratings = ratings.set_index('userId')

ratings.sample(5, random_state=42)

        movieId  rating   timestamp
userId
432       77866     4.5  1335139641
288         474     3.0   978465565
599        4351     3.0  1498524542
42         2987     4.0   996262677
75         1610     4.0  1158989841

In [66]:

UserProfile = ratings.merge(genres, left_on='movieId', right_index=True)
UserProfile = UserProfile.reset_index()

In [70]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(UserProfile, random_state = 42, test_size = .1)

for col in genres.columns:
    train[col] = train[col] * train['rating']

UserProfile = train.groupby('userId')[genres.columns].mean()
UserProfile

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
userId,,,,,,,,,,,,,,,,,,,,
1,0.0,1.650246,1.655172,0.669951,0.896552,1.586207,0.896552,0.000000,1.334975,0.886700,0.000000,0.192118,0.000000,0.443350,0.290640,0.423645,0.729064,0.916256,0.399015,0.103448
2,0.0,1.380952,0.595238,0.000000,0.000000,0.571429,1.023810,0.619048,2.357143,0.000000,0.000000,0.000000,0.714286,0.000000,0.190476,0.214286,0.738095,1.023810,0.214286,0.166667
3,0.0,1.470588,0.867647,0.044118,0.029412,0.250000,0.029412,0.000000,0.176471,0.382353,0.000000,0.970588,0.000000,0.014706,0.147059,0.073529,1.720588,0.720588,0.058824,0.000000
4,0.0,0.352941,0.470588,0.117647,0.186275,1.705882,0.460784,0.039216,1.941176,0.343137,0.058824,0.083333,0.014706,0.313725,0.377451,0.960784,0.151961,0.598039,0.122549,0.151961
5,0.0,0.684211,0.526316,0.578947,0.868421,1.131579,1.105263,0.000000,2.315789,0.684211,0.000000,0.078947,0.289474,0.473684,0.000000,0.684211,0.131579,0.684211,0.263158,0.157895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.422123,0.438988,0.138393,0.152778,1.353671,0.402282,0.018849,2.380952,0.315972,0.022817,0.165179,0.043651,0.147321,0.303075,1.159226,0.255952,0.622024,0.225694,0.055060
607,0.0,1.341615,0.913043,0.093168,0.354037,0.981366,0.478261,0.000000,1.788820,0.397516,0.000000,0.714286,0.031056,0.080745,0.397516,0.577640,0.639752,1.341615,0.111801,0.024845
608,0.0,1.111036,0.698520,0.187079,0.249664,1.161507,0.631225,0.024226,1.149394,0.401077,0.013459,0.401750,0.064603,0.103634,0.266487,0.340511,0.656797,1.106999,0.084118,0.039031
609,0.0,0.848485,0.878788,0.090909,0.181818,0.606061,0.545455,0.181818,1.757576,0.090909,0.000000,0.212121,0.000000,0.000000,0.000000,0.393939,0.363636,1.303030,0.424242,0.121212
610,0.0,1.444113,0.784983,0.199659,0.152304,1.174915,0.784130,0.014078,1.409983,0.422355,0.034556,0.819539,0.233788,0.036263,0.347696,0.339590,0.707338,1.393345,0.134812,0.094710